from enum import Enum


class Route(str, Enum):
    EMERGENCY = "EMERGENCY"
    PUBLIC_RAG = "PUBLIC_RAG"
    PUBLIC_TOOL = "PUBLIC_TOOL"
    AUTHENTICATED_FHIR = "AUTHENTICATED_FHIR"
    FIXED_HYBRID = "FIXED_HYBRID"
    HUMAN_HANDOFF = "HUMAN_HANDOFF"
    UNSUPPORTED = "UNSUPPORTED"


class Intent(str, Enum):
    GREETING = "GREETING"
    HOSPITAL_INFORMATION = "HOSPITAL_INFORMATION"
    HOSPITAL_CONTACT = "HOSPITAL_CONTACT"
    WORKING_HOURS = "WORKING_HOURS"
    DEPARTMENT_INFORMATION = "DEPARTMENT_INFORMATION"
    DOCTOR_INFORMATION = "DOCTOR_INFORMATION"
    DOCTOR_SCHEDULE = "DOCTOR_SCHEDULE"
    APPOINTMENT_GUIDANCE = "APPOINTMENT_GUIDANCE"
    APPOINTMENT_BOOKING = "APPOINTMENT_BOOKING"
    APPOINTMENT_STATUS = "APPOINTMENT_STATUS"
    SERVICE_INFORMATION = "SERVICE_INFORMATION"
    SERVICE_PRICE = "SERVICE_PRICE"
    BHYT_INFORMATION = "BHYT_INFORMATION"
    EXAMINATION_PROCEDURE = "EXAMINATION_PROCEDURE"
    PATIENT_APPOINTMENT = "PATIENT_APPOINTMENT"
    LAB_RESULT = "LAB_RESULT"
    MEDICATION_INFORMATION = "MEDICATION_INFORMATION"
    SYMPTOM_QUESTION = "SYMPTOM_QUESTION"
    EMERGENCY = "EMERGENCY"
    COMPLAINT = "COMPLAINT"
    HUMAN_SUPPORT = "HUMAN_SUPPORT"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    UNKNOWN = "UNKNOWN"


class SafetyFlag(str, Enum):
    NONE = "none"
    EMERGENCY = "emergency"
    OUT_OF_SCOPE = "out_of_scope"
    LOW_CONFIDENCE = "low_confidence"
    MEDICAL_ADVICE = "medical_advice"
    UNAUTHORIZED_PATIENT_ACCESS = "unauthorized_patient_access"


class SourceType(str, Enum):
    RAG = "rag"
    FHIR = "fhir"
    PUBLIC_API = "public_api"
