-- =====================================================================
-- V2__seed_departments.sql
-- Source: data/seed/crawled/departments.json (crawled from official site).
-- =====================================================================

-- departments
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('kham-benh-tu-nguyen', 'Khoa Khám bệnh (Tự nguyện)', 'Khoa lâm sàng. Tiếp nhận khám ngoại trú khu Tự nguyện 1, 2 (CS1) và Tự nguyện (CS2). Bao gồm Đơn nguyên Khám và điều trị tự nguyện. Đặt lịch hẹn trước qua hotline/website/Zalo Mini App.', 'CS1+CS2', NULL, 'TN1/TN2 CS1: 7:00-16:30 (Thứ 2-Thứ 7), Chủ nhật theo lịch bác sĩ trực. TN CS2: 7:00-16:30.', '19001082', 1, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('kham-benh-tu-nguyen-1', 'Khu Khám bệnh Tự nguyện 1 - Cơ sở 1', 'Khu Khám bệnh Tự nguyện 1 tại CS1 (92 Trần Hưng Đạo). Từ 8 phòng khám chính + phòng tăng cường. Lịch khám công bố công khai trên trang ''Lịch làm việc của Bác sỹ''.', 'CS1', 'Tầng 1 (Khu TN1), Tầng 2 (cận lâm sàng cho TN1)', '7:00/7:30 - 16:00/16:30 (Thứ 2-Thứ 7)', NULL, 2, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('kham-benh-tu-nguyen-3', 'Khu Khám bệnh Tự nguyện 3 - Cơ sở 1', 'Khu Khám bệnh Tự nguyện 3 tại CS1. 9 phòng khám + 2 phòng tăng cường.', 'CS1', NULL, '6:30/7:30 - 16:30 (Thứ 2-Thứ 7)', NULL, 3, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('phong-kham-da-khoa-cs2', 'Phòng khám đa khoa - Cơ sở 2', 'Phòng khám đa khoa tại CS2 (695 Lạc Long Quân). Chuyên khoa: Tim mạch, Nhi khoa, Mắt, Tai mũi họng, Răng hàm mặt, Hô hấp, Cơ xương khớp, Y học cổ truyền, Phục hồi chức năng, Sản, Da liễu.', 'CS2', NULL, '7:30-16:30 (Thứ 2-Thứ 6, một số khoa nghỉ Thứ 7-CN)', '02437589090, 0961972097', 4, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('don-vien-can-thiep-tinh-mach', 'Đơn nguyên Can thiệp tĩnh mạch', 'Đơn nguyên can thiệp tĩnh mạch.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('don-vien-chan-doan-hinh-anh-ky-thuat-cao', 'Đơn nguyên Chẩn đoán hình ảnh kỹ thuật cao', 'Đơn nguyên chẩn đoán hình ảnh kỹ thuật cao.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('don-vien-dien-sinh-ly-roi-loan-nhit', 'Đơn nguyên Thăm dò điện sinh lý và rối loạn nhịp', 'Đơn nguyên lâm sàng. Đặt máy tạo nhịp, CRT, ICD, RF.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('don-vien-kham-dieu-tri-tu-nguyen', 'Đơn nguyên Khám và điều trị tự nguyện', 'Đơn nguyên thuộc nhóm lâm sàng.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('don-vien-so-sinh', 'Đơn nguyên Sơ sinh', 'Đơn nguyên sơ sinh.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('don-vien-tim-mach-can-thiep-cs2', 'Đơn nguyên Tim mạch can thiệp cơ sở 2', 'Đơn nguyên can thiệp tim mạch tại CS2.', 'CS2', NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-cac-benh-mach-mau', 'Khoa Các bệnh mạch máu', 'Khoa lâm sàng. Phồng động mạch chủ bụng, hẹp động mạch cảnh, bệnh lý mạch máu các chi.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-cap-cuu', 'Khoa Cấp cứu', 'Khoa lâm sàng. Tiếp nhận cấp cứu 24/7. Bệnh nhân cần can thiệp cấp cứu được thực hiện trong vòng 1 tiếng từ khi đến bệnh viện.', NULL, NULL, '24/7', NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-chan-doan-hinh-anh', 'Khoa Chẩn đoán hình ảnh', 'Khoa cận lâm sàng. MSCT 128 dãy, MRI 1.5 Tesla, 25 máy siêu âm tim (4D). Đơn nguyên Chẩn đoán hình ảnh kỹ thuật cao.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-dieu-tri-ban-ngay', 'Khoa Điều trị ban ngày', 'Khoa điều trị ngoại trú ban ngày. Tiếp nhận bệnh nhân chuyển từ phòng khám theo chỉ định bác sĩ.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-dinh-duong', 'Khoa Dinh dưỡng', 'Khoa cận lâm sàng.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-duoc', 'Khoa Dược', 'Khoa cận lâm sàng. Bao gồm nhà thuốc dịch vụ và quầy thuốc bảo hiểm.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-gay-me-hoi-suc', 'Khoa Gây mê hồi sức', 'Khoa lâm sàng. Gây mê hồi sức cho phẫu thuật tim mạch.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-hoi-suc-tich-cuc', 'Khoa Hồi sức tích cực', 'Khoa lâm sàng. Hồi sức tích cực người lớn.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-hoi-suc-tich-cuc-nhi', 'Khoa Hồi sức tích cực Nhi', 'Khoa lâm sàng. Đơn vị hồi sức tích cực nhi với 12 giường bệnh.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-kiem-soat-nhiem-khuan', 'Khoa Kiểm soát nhiễm khuẩn', 'Khoa cận lâm sàng.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-ngoai', 'Khoa Ngoại', 'Khoa lâm sàng. Phẫu thuật tim mạch (tim bẩm sinh phức tạp, tim mắc phải, mạch máu ngoại vi).', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-noi', 'Khoa Nội', 'Khoa lâm sàng. Chẩn đoán, điều trị nội khoa Tim mạch - chuyển hóa.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-noi-nhi', 'Khoa Nội Nhi', 'Khoa lâm sàng. Tim mạch nhi - điều trị nội trú nhi.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-tim-mach-can-thiep', 'Khoa Tim mạch can thiệp', 'Khoa lâm sàng. Can thiệp ĐMC vành, nong van hai lá, stent graft ĐMC chủ, thay van ĐMC qua da (TAVI), điện sinh lý tim, đặt máy tạo nhịp/CRT/ICD, RF. Đơn vị chăm sóc mạch vành. 3 phòng Cathlab.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-tim-mach-chuyen-hoa', 'Khoa Tim mạch chuyển hóa', 'Khoa lâm sàng. Khám và điều trị đái tháo đường, rối loạn mỡ máu, quản lý bệnh mạn tính, điều trị bàn chân đái tháo đường.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('khoa-xet-nghiem', 'Khoa Xét nghiệm', 'Khoa cận lâm sàng.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('phong-cong-nghe-thong-tin', 'Phòng Công nghệ thông tin', 'Phòng chức năng.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('phong-cong-tac-xa-hoi', 'Phòng Công tác xã hội', 'Phòng chức năng. Tổ chăm sóc khách hàng, tư vấn đặt lịch. Điện thoại 02439425880.', NULL, NULL, NULL, '02439425880', 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('phong-dieu-duong', 'Phòng Điều dưỡng', 'Phòng chức năng.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('phong-hanh-chinh-quan-tri', 'Phòng Hành chính quản trị', 'Phòng chức năng.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('phong-ke-hoach-tong-hop', 'Phòng Kế hoạch tổng hợp', 'Phòng chức năng.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('phong-quan-ly-chat-luong-benh-vien', 'Phòng Quản lý chất lượng Bệnh viện', 'Phòng chức năng. ISO 9001:2008.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('phong-tai-chinh-ke-toan', 'Phòng Tài chính kế toán', 'Phòng chức năng. Thu phí, duyệt BHYT, đồng chi trả.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('phong-to-chuc-can-bo', 'Phòng Tổ chức cán bộ', 'Phòng chức năng.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('phong-vat-tu-thiet-bi-y-te', 'Phòng Vật tư - Thiết bị y tế', 'Phòng chức năng.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.departments (code, name, description, campus, floor, working_hours, phone, sort_order, is_active) VALUES ('trung-tam-dao-tao-chi-dao-tuyen', 'Trung tâm Đào tạo và Chỉ đạo tuyến', 'Trung tâm đào tạo, chỉ đạo tuyến và chuyển giao kỹ thuật.', NULL, NULL, NULL, NULL, 100, TRUE) ON CONFLICT (code) DO NOTHING;
