-- =====================================================================
-- V3__seed_doctors.sql
-- Sources: data/seed/crawled/doctors.json (authoritative) + schedule-only
--          doctors parsed from raw schedule (not in crawled roster).
-- No bio/avatar fabricated (R1). schedule-derived records flagged.
-- =====================================================================

-- doctors
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('bui-thi-thanh-ha', 'Bùi Thị Thanh Hà', 'TS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('chu-thi-hang', 'Chu Thị Hằng', 'BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('duong-thi-thuy-nga', 'Dương Thị Thúy Nga', 'ThS.BS', NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), 'Trực phòng PK Nhi (P402) CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('hoang-minh-loi', 'Hoàng Minh Lợi', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('hoang-van', 'Hoàng Văn', 'TS.BS', 'Phó Giám đốc Bệnh viện', (SELECT id FROM hospital.departments WHERE code = 'khoa-tim-mach-can-thiep'), 'Trang ''Giới thiệu chung'' mô tả: ''TS.BS Hoàng Văn – Phó Giám đốc Bệnh viện, chuyên gia hàng đầu về can thiệp tim mạch cùng đội ngũ chuyên gia giỏi nhất trong lĩnh vực tim mạch can thiệp thực hiện.'' Cũng trực phòng khám số 4 khu TN1-CS1.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('ha-mai-huong', 'Hà Mai Hương', 'TS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('linh-the-cuong', 'Linh Thế Cường', 'ThS.BS', NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), 'Trực phòng TMH (P402) CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('le-quang-huy', 'Lê Quang Huy', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('le-thanh-nam', 'Lê Thanh Nam', 'BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('le-thuy-ngoc', 'Lê Thuý Ngọc', 'ThS.BS', NULL, NULL, 'Trực phòng khám 311 CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('le-the-kien', 'Lê Thế Kiên', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('le-thi-hoai-thu', 'Lê Thị Hoài Thu', 'BSCKII', NULL, NULL, 'Trực phòng khám 306 CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('le-thi-thao', 'Lê Thị Thảo', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('lai-thi-bach-yen', 'Lại Thị Bạch Yến', 'ThS.BS', NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), 'Trực phòng P405.A CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-danh-sen', 'Nguyễn Danh Sen', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-duy-chinh', 'Nguyễn Duy Chinh', 'ThS.BS', NULL, NULL, 'Trực phòng khám 309 CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-mai-huong', 'Nguyễn Mai Hương', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-ngoc-tan', 'Nguyễn Ngọc Tân', 'BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-phuong-lien', 'Nguyễn Phương Liên', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-quoc-hung', 'Nguyễn Quốc Hùng', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-sinh-hien', 'Nguyễn Sinh Hiền', 'PGS.TS.BS', 'Giám đốc Bệnh viện', NULL, 'PGS.TS.BS Nguyễn Sinh Hiền - thành viên Ban lãnh đạo hiển thị trên trang ''Ban lãnh đạo''. Là người phê duyệt QT.25.01 (Quy trình đón tiếp bệnh nhân khu TN1-CS1) với vai trò Giám đốc.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-thanh-tra', 'Nguyễn Thanh Trà', 'BS', NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), 'Trực phòng RHM (P401) CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-the-nam-huy', 'Nguyễn Thế Nam Huy', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-thi-huyen', 'Nguyễn Thị Huyền', 'BSCKI', NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), 'Trực phòng Mắt (P405.D) CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-thi-minh-hoa', 'Nguyễn Thị Minh Hoa', 'ThS.BS', NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), 'Trực phòng Da liễu (P403) CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-thi-minh-nguyet', 'Nguyễn Thị Minh Nguyệt', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-thi-quynh-trang', 'Nguyễn Thị Quỳnh Trang', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-thi-thu-thuy', 'Nguyễn Thị Thu Thủy', 'TS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-thi-thuan', 'Nguyễn Thị Thuận', 'BSNT', NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), 'Trực phòng YHCT (P404) CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-thi-tuyet-mai', 'Nguyễn Thị Tuyết Mai', 'BSCKII', NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), 'Trực phòng Sản (P403) CS2, sáng.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-thi-viet-nga', 'Nguyễn Thị Việt Nga', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-toan-thang', 'Nguyễn Toàn Thắng', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-trung-hieu', 'Nguyễn Trung Hiếu', 'BSCKI', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-van-dan', 'Nguyễn Văn Dần', 'BSCKII', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-van-thuc', 'Nguyễn Văn Thực', 'BSCKII', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-xuan-tuan', 'Nguyễn Xuân Tuấn', 'TS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-xuan-tu', 'Nguyễn Xuân Tú', 'TS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-inh-hong-phuc', 'Nguyễn Đình Hồng Phúc', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('nguyen-inh-phuc', 'Nguyễn Đình Phúc', 'BS', NULL, NULL, 'Trực phòng khám TN mức 3 thứ 7 CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('ngo-van-thanh', 'Ngô Văn Thanh', 'TS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('phan-thanh-nam', 'Phan Thành Nam', 'BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('pham-nhu-hung', 'Phạm Như Hùng', 'TS.BS', NULL, NULL, 'Thành viên Ban lãnh đạo hiển thị trên trang ''Ban lãnh đạo''. Trực phòng khám số 1 khu TN1-CS1 trong lịch khám.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('pham-quang-huy', 'Phạm Quang Huy', 'BSCKII', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('pham-thi-an', 'Phạm Thị An', 'BSCKII', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('pham-thi-hoa', 'Phạm Thị Hoa', 'BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('pham-thi-oanh', 'Phạm Thị Oanh', 'ThS.BSNT', NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), 'Trực phòng P405.B CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('pham-van-tung', 'Phạm Văn Tùng', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('pham-ang-anh', 'Phạm Đăng Anh', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('tran-ngoc-dung', 'Trần Ngọc Dũng', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('tran-sinh-cuong', 'Trần Sinh Cường', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('tran-thanh-hoa', 'Trần Thanh Hoa', 'BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('tran-thi-an', 'Trần Thị An', 'TS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('tran-thi-linh-tu', 'Trần Thị Linh Tú', 'TS.BS', NULL, NULL, 'Trực phòng khám 308 CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('tran-thi-ngoc-lan', 'Trần Thị Ngọc Lan', 'TS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('tran-thi-quynh-nga', 'Trần Thị Quỳnh Nga', 'BSNT', NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), 'Trực phòng PHCN (P401) CS2.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('tran-thi-thanh-ha', 'Trần Thị Thanh Hà', 'BSCKII', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('tran-ac-long', 'Trần Đắc Long', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('vo-thi-ngoc-anh', 'Võ Thị Ngọc Anh', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('vu-quynh-nga', 'Vũ Quỳnh Nga', 'TS.BS', NULL, NULL, 'Thành viên Ban lãnh đạo hiển thị trên trang ''Ban lãnh đạo''. Cũng trực phòng khám số 2 khu TN1-CS1 trong lịch khám.', NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('vu-thi-trang', 'Vũ Thị Trang', 'BSCKII', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('inh-hai-nam', 'Đinh Hải Nam', 'BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('inh-quang-huy', 'Đinh Quang Huy', 'TS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('ao-thi-thu-ha', 'Đào Thị Thu Hà', 'BSCKI', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('ang-duong', 'Đăng Dương', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('o-thi-van-anh', 'Đỗ Thị Vân Anh', 'ThS.BS', NULL, NULL, NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('le-thi-kien', 'Lê Thị Kiến', 'ThS.BS', NULL, (SELECT id FROM hospital.departments WHERE code = 'kham-benh-tu-nguyen-3'), NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('sths-bs-nguyen-inh-hong-phuc', 'SThS.BS Nguyễn Đình Hồng Phúc', NULL, NULL, (SELECT id FROM hospital.departments WHERE code = 'kham-benh-tu-nguyen-3'), NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('ths-bs-tran-ac-long', 'ThS. BS Trần Đắc Long', NULL, NULL, (SELECT id FROM hospital.departments WHERE code = 'kham-benh-tu-nguyen-3'), NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.doctors (code, full_name, degree, title, department_id, bio, avatar_url, is_active) VALUES ('ths-bsnt-pham-thi-oanh', 'ThS.BSNT Phạm Thị Oanh', NULL, NULL, (SELECT id FROM hospital.departments WHERE code = 'phong-kham-da-khoa-cs2'), NULL, NULL, TRUE) ON CONFLICT (code) DO NOTHING;
