-- =====================================================================
-- V6__seed_bhyt_policies.sql
-- Source: data/seed/crawled/bhyt-policies.json (verbatim from official site).
-- =====================================================================

-- bhyt_policies
INSERT INTO hospital.bhyt_policies (code, title, category, summary, details_md, source_url, effective_date) VALUES ('bhyt-bang-gia-cu-phap', 'Cơ sở pháp lý Bảng giá BHYT áp dụng tại Bệnh viện Tim Hà Nội', 'general', 'Bảng giá BHYT áp dụng theo Thông tư 22/2023/TT-BYT hiện hành; một số mục Chụp cắt lớp vi tính áp dụng thêm điều kiện thanh toán tại Thông tư 13/2020/TT-BYT.', 'Sở Y tế Hà Nội - Bệnh viện Tim Hà Nội. Bảng giá Bảo hiểm y tế (gồm 6 danh mục: Khám bệnh & ngày giường, Xét nghiệm, Thủ thuật & Chẩn đoán hình ảnh, Chụp cộng hưởng từ, Chụp cắt lớp vi tính, Can thiệp tim mạch). Ghi chú chung: ''Bảng giá BHYT áp dụng theo Thông tư số 22/2023/TT-BYT của Bộ Y tế hiện hành (một số mục Chụp cắt lớp vi tính áp dụng thêm điều kiện thanh toán tại Thông tư số 13/2020 của Bộ Y tế hiện hành)''. Đơn vị tính: VNĐ.', 'https://benhvientimhanoi.vn/vn/huong-dan-kham-benh/bang-gia-dich-vu', NULL) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.bhyt_policies (code, title, category, summary, details_md, source_url, effective_date) VALUES ('bhyt-gia-kham-benh-giuong', 'Mức giá BHYT chi trả tối đa - Khám bệnh và ngày giường điều trị', 'general', 'Khám bệnh: 42.100đ. Giường Nội khoa: 255.300đ. Giường Hồi sức cấp cứu: 474.700đ. Giường Hồi sức tích cực: 786.300đ. Giường Ngoại khoa loại 1-4: 242.100 - 339.000đ.', 'Bảng giá BHYT - Khám bệnh và ngày giường (đơn vị VNĐ): Khám bệnh 42.100 | Giường Nội khoa 255.300 | Giường Hồi sức cấp cứu 474.700 | Giường Hồi sức tích cực 786.300 | Giường Ngoại khoa loại 1: 339.000 | loại 2: 308.500 | loại 3: 270.500 | loại 4: 242.100.', 'https://benhvientimhanoi.vn/vn/huong-dan-kham-benh/bang-gia-dich-vu', NULL) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.bhyt_policies (code, title, category, summary, details_md, source_url, effective_date) VALUES ('bhyt-the-vssid-cccd-chip', 'Sử dụng thẻ BHYT điện tử (VssID) hoặc CCCD gắn chip thay thẻ BHYT giấy', 'cardiac', 'BN không mang thẻ BHYT giấy được sử dụng hình ảnh BHYT trên ứng dụng VssID hoặc CCCD gắn chip có tích hợp thẻ BHYT thay thế.', 'Quy trình đón tiếp tại Khu TN1 CS1 (QT.25.01): ''Bệnh nhân khám BHYT xuất trình giấy chuyển viện, giấy hẹn khám lại, thẻ BHYT (trong trường hợp không mang thẻ BHYT đến khám, chữa bệnh được sử dụng hình ảnh BHYT trên ứng dụng Vss - ID hoặc CCCD gắn chíp có tích hợp thẻ BHYT thay thế cho việc sử dụng thẻ BHYT giấy), CCCD hoặc giấy tờ tùy thân có ảnh''.', 'https://benhvientimhanoi.vn/vn/huong-dan-kham-benh/quy-trinh-kham-chua-benh', NULL) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.bhyt_policies (code, title, category, summary, details_md, source_url, effective_date) VALUES ('bhyt-giay-chuyen-tuyen', 'Thủ tục khám BHYT tuyến chuyên khoa - Giấy chuyển tuyến & cam kết đồng chi trả', 'cross_ref', 'BN có giấy chuyển tuyến mới được khám BHYT tại BV Tim Hà Nội (tuyến chuyên khoa). Phải ký cam kết đồng ý chi trả khoản chênh lệch giá dịch vụ y tế khi KCB tại bệnh viện chuyên khoa.', 'Quy trình QT.25.01: ''Bệnh nhân có giấy chuyển tuyến mới được hướng dẫn ký cam kết đồng ý chi trả khoản chênh lệch giá dịch vụ y tế khi khám, chữa bệnh tại Bệnh viện Tim Hà Nội''. Khi đủ ĐK tham gia BHYT cả năm: đóng dấu chương trình quản lý bệnh mạn tính - không cần xin giấy chuyển. Hồ sơ ngoại trú khám lần 2: đóng dấu hẹn khám lần 2 và ngày chuyển tuyến. Sau lần 2: phải xin giấy chuyển tuyến mới.', 'https://benhvientimhanoi.vn/vn/huong-dan-kham-benh/quy-trinh-kham-chua-benh', NULL) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.bhyt_policies (code, title, category, summary, details_md, source_url, effective_date) VALUES ('bhyt-dong-chi-tra', 'Đồng chi trả BHYT tại quầy kế toán', 'copay', 'Kế toán thu tiền đồng chi trả theo mức hưởng của thẻ BHYT và số tiền chênh lệch với đơn thuốc BHYT (nếu có). BN mua thuốc dịch vụ thanh toán tại quầy thuốc dịch vụ.', 'Bước 11 - QT.25.01: ''Kế toán thu tiền đồng chi trả theo mức hưởng của thẻ BHYT và số tiền chênh lệch với đơn thuốc bảo hiểm (nếu có). Bệnh nhân mua thuốc dịch vụ thanh toán tiền thuốc cho kế toán tại quầy thuốc dịch vụ. Nhân viên kế toán đóng dấu đã thu tiền vào đơn thuốc và mời BN đi lĩnh thuốc BHYT hoặc mua thuốc dịch vụ.''', 'https://benhvientimhanoi.vn/vn/huong-dan-kham-chua-benh/quy-trinh-kham-chua-benh', NULL) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.bhyt_policies (code, title, category, summary, details_md, source_url, effective_date) VALUES ('bhyt-thu-tuc-hen-kham-lai', 'Thủ tục hẹn khám lại và chuyển tuyến (BN BHYT ngoại trú)', 'copay', 'Điều dưỡng bàn hẹn khám lại đóng dấu chương trình quản lý bệnh mạn tính hoặc đóng dấu hẹn khám lần 2 + ngày chuyển tuyến. BN chương trình BHYT cả năm không cần xin giấy chuyển.', 'Bước 9 - QT.25.01: Với BN khám BHYT chưa có hồ sơ ngoại trú: (a) Nếu BN không đủ ĐK tham gia chương trình BHYT cả năm: đóng dấu hẹn khám lần 2 và ngày chuyển tuyến lên giấy hẹn khám lại; (b) Nếu BN đủ ĐK tham gia chương trình BHYT cả năm, đóng dấu chương trình phù hợp lên giấy hẹn khám lại và hướng dẫn BN không cần xin giấy chuyển. Với BN BHYT đã có hồ sơ ngoại trú: hồ sơ đã khám lần 2 → hướng dẫn BN lần tái khám sau xin giấy chuyển tuyến mới; hồ sơ đang theo chương trình → tiếp tục đóng dấu chương trình.', 'https://benhvientimhanoi.vn/vn/huong-dan-kham-benh/quy-trinh-kham-chua-benh', NULL) ON CONFLICT (code) DO NOTHING;
INSERT INTO hospital.bhyt_policies (code, title, category, summary, details_md, source_url, effective_date) VALUES ('bhyt-uu-tien', 'Đối tượng ưu tiên theo Quy định số 154 của Bệnh viện Tim Hà Nội (12/01/2024)', 'general', 'BN thuộc đối tượng ưu tiên theo Quy định 154/QĐ-BV (ban hành 12/01/2024) được đóng dấu ''ưu tiên'' trên sổ khám và phục vụ ưu tiên tại quầy kế toán và bàn đo DHST.', 'QT.25.01 Bước 3: ''Những BN thuộc đối tượng ưu tiên (theo quy định số 154 của BVT ban hành ngày 12/01/2024) sẽ được nhân viên đóng dấu ưu tiên lên trên sổ khám.'' Bước 4-5: Hướng dẫn sang quầy kế toán ưu tiên và đo DHST ưu tiên. (Nội dung chi tiết danh mục đối tượng ưu tiên không hiển thị văn bản trên trang công khai - cần xin văn bản Quy định 154/QĐ-BV từ bệnh viện.)', 'https://benhvientimhanoi.vn/vn/huong-dan-kham-benh/quy-trinh-kham-chua-benh', NULL) ON CONFLICT (code) DO NOTHING;
